[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# API proxy to Sanity (optional, if CORS issues)
[[redirects]]
  from = "/api/sanity/*"
  to = "https://832k5je1.api.sanity.io/:splat"
  status = 200
  force = true